name: Inyon
options:
  bundleIdPrefix: com.inyon
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 11.0.0

targets:
  Inyon:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.yml"
          - ".git/**"
          - "Tests/**"
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.inyon.app
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
      SWIFT_EMIT_LOC_STRINGS: YES

  InyonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Inyon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.inyon.app.tests
      GENERATE_INFOPLIST_FILE: YES
